hello:
	java -jar jasmin.jar ./hello.j

print1:
	java -jar jasmin.jar ./print1.j
	java Print1

sum:
	java -jar jasmin.jar ./sum.j
	java Sum1

vardec:
	java -jar jasmin.jar ./vardec.j
	java Vardec

forloop:
	java -jar jasmin.jar ./forloop.j
	java Forloop

clean:
	rm -rf *.class


